// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef cwioUI_h
#define cwioUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "status.h"
#include "cwio.h"
#include "ValueSlider.h"
extern Fl_Input2 *txt_to_send;
#include <FL/Fl_Group.H>
#include "flslider2.h"
extern Fl_Value_Slider2 *sldr_cwioWPM;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_cwio_config;
extern Fl_Button *btn_cwio_clear;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *btn_cwioSEND;
extern Fl_Button *btn_msg[12];
Fl_Double_Window* cwio_window();
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Box.H>
#include "flinput2.h"
extern Fl_Input2 *edit_label[12];
extern Fl_Input2 *edit_msg[12];
extern Fl_Button *btn_cancel_edit;
extern Fl_Button *btn_apply_edit;
extern Fl_Button *btn_done_edit;
Fl_Double_Window* make_message_editor();
#include "combo.h"
extern Fl_ComboBox *select_cwioPORT;
extern Fl_Light_Button *btn_cwioCONNECT;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btn_cwioCAT;
extern Fl_Check_Button *btn_cwioAUX;
extern Fl_Check_Button *btn_cwioSEP;
extern Fl_ListBox *listbox_cwioKEYLINE;
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *cntr_cwioPTT;
extern Fl_Light_Button *btn_cw_dtr_calibrate;
#include <FL/Fl_Counter.H>
extern Fl_Counter *cnt_cwio_comp;
Fl_Double_Window* cwio_config_dialog();
#endif
